### ISSUE TITLE
List events filter by month and not only by year

### ISSUE THREAD

**Issue by graphema** [ChurchInfo/ChurchInfo#12]
I think that would be an improvement if we can get the list events filter by month and year, and not only by year. Anyone agrees?

**Comment by DawoudIO** [comment]
Hi @graphema, we would love feedback on Events we are thinking of revamping it but not sure how it is used today.

**Comment by DawoudIO** [comment]
@graphema, please join us in the ChurchCRM/CRM project as that is where we manage new changes to the ChurchCRM project, for ChurchInfo the sourceforge.net space is where you can ask Qs.
