### ISSUE TITLE
Logins

### ISSUE THREAD

**Issue by Bilasio** [ChurchInfo/ChurchInfo#18]
Please i can not login i am stuck at the login page

**Comment by DawoudIO** [comment]
Hi @bilasio, are you running churchinfo or ChurchCRM 

for ChurchCRM Pease join us on that project gitter.im or file an issue... most likely you don't have all the requirements 


I'm afraid this project space is not active for ChurchInfo

**Comment by Bilasio** [comment]
Thank you sir am using a  churchcrm

Joseph Bilasio
