### ISSUE TITLE
Tax Report- Wrong Fiscal Year

### ISSUE THREAD

**Issue by aharris88** [ChurchInfo/ChurchInfo#2]
My church is generating tax reports and we were having trouble with this line of code. It was always saying "Fiscal Year 2015" even though we were generating reports for 2014.

https://github.com/ChurchInfo/ChurchInfoWeb/blob/church/stgeorgecoptic/churchinfo/Reports/TaxReport.php#L213

The issue is also mentioned here: http://sourceforge.net/p/churchinfo/discussion/401180/thread/b85b7657/?limit=25#236c

**Comment by gdawoud** [comment]
Hi,  

I have not had a chance to look deeply but try to add the following url parameter FYID=2014

**Comment by aharris88** [comment]
Good idea.

**Comment by DawoudIO** [comment]
@aharris88 I'm closing this ticket and tracking the issue on our new https://github.com/ChurchCRM/CRM project

**Comment by aharris88** [comment]
Thanks.
