### ISSUE TITLE
Problem with the 2.7.5

### ISSUE THREAD

**Issue by phili67** [ChurchInfo/ChurchInfo#35]
I've corrected some Bugs, for localisation the directory should be :
skin/locale/dataTables/ and not skin/locale/datatables/

Second there is a bug is the UserEditor.php file.
When I try to add a new user, I ever get a blank page (nothing inside).

Last when I try to quickly add members to a group in the GroupView.php file, there's two bugs :
GroupView.php?GroupID=1
1) I don't get the result directly I have to reload the page to see the result.
2) I have in the table (null null for adress), 
3) last when I select a line, it's impossible to suppress them with the button below.

Suggestion, in the query menu when I select some people in the cart, It should be a nice idea to add them directly in a group....

Thank's

**Comment by crossan007** [comment]
this is opened against the wrong project.  please report bugs here https://github.com/churchcrm/crm/issues
