### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by telx85** [ChurchInfo/ChurchInfo#4]
G'day mate,

Just checking out your changes compared to the main. I'm getting an error message that I'm pretty sure means that your version is one behind the main.

There is an incompatibility between database schema and PHP script. You are seeing this message because there is a software bug.
Please post to the ChurchInfo Help forum for assistance. 
ChurchInfo MySQL Version = 1.2.14
ChurchInfo PHP Version = 1.2.13

Any ideas?

**Comment by gdawoud** [comment]
You are missing a SQL Script that is not part of the main install, I'll try to fix that tonight and put full install instructions  

please run the following script to fix your issue

https://github.com/ChurchInfo/ChurchInfoWeb/blob/ea5d20f77789e1bc4834326a78fc61184669bab3/churchinfo/SQL/menu_update.sql

**Comment by telx85** [comment]
I ran that menu update script (said it did 14 changes and finished successfully) but it still shows the same error.

**Comment by gdawoud** [comment]
Can you send me a screen shot also if this is a new install or upgrade

**Comment by telx85** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2740134/6207337/579df30a-b5da-11e4-8da7-6c2c553614f3.png)
complete new install. I used the latest version available, then copied your version over the other version. Maybe that is my problem. Anyway I then did your .sql upgrade and still an issue.

**Comment by gdawoud** [comment]
Ya :( I think i did that by error trying to sync with the SF build... 

Please update the following file  churchinfo/CheckVersion.php

Replace 
$_SESSION['sChurchInfoPHPVersion'] = '1.2.13';
With 
$_SESSION['sChurchInfoPHPVersion'] = '1.2.14';


I'm working on cleaning all of this, I guess you got a build mind way my changes... 

Sorry please let me know if that works. 

G

**Comment by telx85** [comment]
Yep that works. 

Cheers.
