### ISSUE TITLE
ChurchWebCRM: Demo not working

### ISSUE THREAD

**Issue by rrjanbiah** [ChurchInfo/ChurchInfo#6]
1. Please enable Issue reporting for ChurchWebCRM fork
2. Demo for ChurchWebCRM is not working (Would like to check new features or missing features when compared to churchdb)

**Comment by gdawoud** [comment]
Sorry just noticed this... will do..

**Comment by gdawoud** [comment]
Ah... i see it was moved to http://demo.churchwebcrm.com

**Comment by gdawoud** [comment]
the username/password are admin/george note... I'll move it to the new domain of churchcrm.io
